### ISSUE TITLE
No se muestra bien el dashboard de administración de elecciones

### ISSUE THREAD

**Issue by alvarovp27** [EGC1617Grupo/agora-gui-admin#1]
- En la vista de dashboard, donde se puede administrar una elección, cuando la pantalla es muy pequeña, no se muestra de forma correcta, ya que se solapan los elementos.

![image](https://cloud.githubusercontent.com/assets/10280862/20627999/e4a086ee-b323-11e6-9f96-eb8ae6cf08fa.png)
- Se espera que se vean todos los elementos de una forma clara y legible
- [https://agora/admin/dashboard/:id](url)

**Comment by alvarovp27** [comment]
Solucionado. Durante la resolución del presente issue, se aportaron dos alternativas, decantándonos finalmente por la última al ser la que más código permitía reutilizar.

El problema venía por las etiquetas "stick" y "col-xs-2". La primera era la que ponía las barras horizontales que unía cada estado. La segunda, hacía que se mostrara todo en la misma fila (cada estado en una columna). La intención era, que aparecieran todos los estados en la misma columna, y eliminar los nexos entre estado, por lo que la solución, en un principio pasaría por cambiar las clases CSS de ambos elementos: cuando la pantalla fuere menor de 768px, que no se tuviera en cuenta la clase stick, y cambiara col-xs-2 por row.

Se ha trabajado sobre los siguientes ficheros, dentro de agora-gui-admin:
- avAdmin/admin-directives/dashboard/dashboard.html
- avAdmin/admin-directives/dashboard/dashboard.less

PRIMERA ALTERNATIVA (descartada):
Duplicar el código HTML del fragmento afectado en dashboard.html, jugando con las etiquetas hidden-xs:

```HTML
    <div class="statusbar row text-center">
        <div class="hidden-xs">
            <div class="col-xs-2" ng-class="{true:'text-success', false:'text-muted'}[index > $index]" ng-repeat="status in statuses">
                <div class="stick" ng-class="{'stickini': $first, 'stickend': $last}">
					[...]
                </div>
					[...]
            </div>
        </div>
        <div class="hidden-sm hidden-md hidden-lg" >
            <div class="row" ng-class="{true:'text-success', false:'text-muted'}[index > $index]" ng-repeat="status in statuses">
                <div ng-class="{'stickini': $first, 'stickend': $last}">
					[...]
                </div>
					[...]
            </div>
        </div>
    </div>
```

SOLUCIÓN:
Debido a la alta cantidad de código que se duplicaba, se decidió tomar otra alternativa, esta vez con las media queries (@media). Se modificó el fichero dashboard.less de la siguiente manera:
```CSS
  @media screen and (min-width:768px){
    .stick {
        background-image: url("/admin/img/stick-green.png");
        background-repeat: no-repeat;
        background-position: center;
        background-size: 100% 8px;
    }

    .stickend,
    .stickini {
        background-size: 50% 8px;
    }

    .stickini {
        background-position: center right;
    }
    .stickend {
        background-position: center left;
    }

    .stick i {
        background-color: white;
        padding: 4px;
    }

    .stick i.fa-spin {
        background-color: transparent;
    }

    .text-muted .stick {
        background-image: url("/admin/img/stick-gray.png");
    }
  }
```
En este fragmento, se muestra que todas las etiquetas stick (referentes a los nexos horizontales que unen los estados), han sido encapsulados dentro de una media query, indicando que esas clases se aplicarán únicamente cuando el tamaño de la pantalla sea mayor de 768px.

```CSS
  .status-responsive{
    @media (min-width:768px){
      position: relative;
      min-height: 1px;
      width:16.666666666666664%;
      float:left;
      padding: 0px;
    }

    @media (max-width: 767px){
      .row
    }
  }
```
En este otro fragmento, se crea la clase status-responsive, para sustituir col-xs-2. Dentro de la clase hay dos media queries: 
- la primera, se aplica cuando la pantalla es mayor de 768px. Es una réplica de la clase col-xs-2. Para evitar la duplicación de código, se intentó poner simplemente .col-xs-2, de forma que heredara las características de dicha clase, pero daba fallos al compilar los ficheros .less, ya que la clase col-xs-2 está definida en otro proyecto.
- la segunda, se aplica cuando la pantalla es menor de 767px. Aplica la clase row.

Con esto, queda solucionada esta issue.

Imágen con el aspecto tras la solución:
![image](https://cloud.githubusercontent.com/assets/10280862/20834231/805b36e0-b894-11e6-9da6-23e2b0c9f730.png)
